### ISSUE TITLE
ModuleNotFoundError: No module named 'oobleck.csrc’ 

### ISSUE THREAD

**Issue by yyyyyt123** [insujang/oobleck#13]
Hello,

I am new to distributed training. When using the `develop` branch in Oobleck repo for multi-node training, I encountered the following error: ModuleNotFoundError: No module named 'oobleck.csrc’ in distributed training. 

I followed the instructions to set the Oobleck conda environment. The training script I am using is:

+ First, launch the master daemon in machine xxx1 using `python -m oobleck.elastic.master --ip xxx1 --port 8080`. 

+ Then, use another machine to send the training job `python -m oobleck.run --config_path examples/gpt2.yaml --node_ips xxx1 xxx2 --master_ip xxx1 --master_port 8080`

+ Next, I open the log file; it shows the following errors:
``` 
[2023-10-04 14:29:23,199] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/home/ytyang/anaconda3/envs/oobleck/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ytyang/anaconda3/envs/oobleck/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ytyang/anaconda3/envs/oobleck/lib/python3.10/site-packages/oobleck-0.1.0-py3.10-linux-x86_64.egg/oobleck/elastic/agent.py", line 13, in <module>
    from oobleck.csrc.planning.pipeline_template import get_profile_results
ModuleNotFoundError: No module named 'oobleck.csrc'
```

Do you have any suggestions for solving the problem? 

Thanks!

**Comment by insujang** [comment]
Hi @yyyyyt123 , have you seen Oobleck package was successfully installed? I think it failed, probably due to lack of submodules. Please run:
```
git submodule update --init --recursive
pip install . (at the Oobleck root directory)
```

Let me know if it works. Thanks!

**Comment by yyyyyt123** [comment]
Hi @insujang. Thanks for your kind reply. I followed the instructions provided in `README.md` and reinstalled Oobleck from scratch using the following script. 

```
conda activate oobleck
git clone https://github.com/SymbioticLab/Oobleck.git -b develop
cd Oobleck
git submodule update --init --recursive
pip install .
```
The information displayed on the terminal indicates that I have successfully installed the Oobleck.
``` 
Successfully built oobleck
Installing collected packages: oobleck
Successfully installed oobleck-0.1.0
```

However, while trying multi-node oobleck training, the `No module named 'oobleck.csrc'` error still occurred in the log file.

Training script:

``` shell
# launch master daemon
python -m oobleck.elastic.master --ip projgpu22.cse.cuhk.edu.hk --port 8080 
# submit training job
python -m oobleck.run --config_path examples/gpt2.yaml --node_ips projgpu22.cse.cuhk.edu.hk --master_ip projgpu22.cse.cuhk.edu.hk --master_port 8080 
```
The output of the daemon process:
``` shell
[2023-10-04 21:42:42,907] [INFO] [master.py:241:on_connected] Received request: RequestType.LAUNCH_JOB
[2023-10-04 21:42:43,368] [INFO] [master.py:77:run_node_agents] Launching an agent on projgpu22.cse.cuhk.edu.hk: /bin/bash -ic "conda run --no-capture-output -n oobleck python -m oobleck.elastic.agent --master_ip projgpu22.cse.cuhk.edu.hk --master_port 8080 --job_id 2 --agent_index 0"
[2023-10-04 21:42:43,577] [INFO] [master.py:86:run_node_agents] Agent projgpu22.cse.cuhk.edu.hk output will be written at /tmp/oobleck/logs/10-04-2023-21-42-42-gpt2/projgpu22.cse.cuhk.edu.hk.out.
```

The output of the log file:
``` shell
[2023-10-04 21:42:48,699] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/home/ytyang/anaconda3/envs/oobleck/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ytyang/anaconda3/envs/oobleck/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ytyang/anaconda3/envs/oobleck/lib/python3.10/site-packages/oobleck/elastic/agent.py", line 13, in <module>
    from oobleck.csrc.planning.pipeline_template import get_profile_results
ModuleNotFoundError: No module named 'oobleck.csrc'
ERROR conda.cli.main_run:execute(49): `conda run python -m oobleck.elastic.agent --master_ip projgpu22.cse.cuhk.edu.hk --master_port 8080 --job_id 2 --agent_index 0` failed. (See above for error)
```



Do you have any additional information regarding how to fix this error? Thanks!

**Comment by insujang** [comment]
Thank you for reporting. Should be a bug during pybind11 library installation :( I think it happens when Oobleck is not installed in editable mode. I will make a fix for it. In the meantime, could you try `pip install -e .` and run?

**Comment by yyyyyt123** [comment]
Thanks for the reply. I was able to get Oobleck working by using `pip install -e .` !
