### ISSUE TITLE
IndexError: map::at in create_pipeline_templates while trying multi-GPU per node distributed training

### ISSUE THREAD

**Issue by yyyyyt123** [insujang/oobleck#14]
Hi,

I have been using Oobleck for distributed training, with one GPU per node and everything is working fine. However, I decided to try training with multiple GPUs per node, using two nodes and two GPUs per node (overall four GPUs). Unfortunately, I encountered some errors when attempting to do so. Here is the commands I am using for training:

``` shell
# launch master node
python -m oobleck.elastic.master --ip 137.189.88.130 --port 808
# submit training job
python -m oobleck.run --config_path examples/gpt2.yaml --node_ips 137.189.88.130 137.189.88.205 --master_ip 137.189.88.130 --master_port 8080  --num_workers 2

```

This is my agent training log
```
[2023-10-09 19:44:10,691] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
mb size: 14, ar across: 14, ar in: 14
Loading done. creating layer execution results...
Returning from get_profiler_results
[2023-10-09 19:44:12,925] [INFO] [agent.py:128:_launch_workers] Job arguments: OobleckArguments(dist=DistributedArguments(master_ip='projgpu22.cse.cuhk.edu.hk', master_port=8080, node_ips=['137.189.88.130', '137.189.88.205'], node_port=22, num_workers=2, num_agents_per_node=1, username='ytyang'), job=JobArguments(fault_threshold=1, microbatch_size=8, global_microbatch_size=128, steps=30), model=ModelArguments(model_name='gpt2', model_tag='medium', dataset_path='wikitext', dataset_name='wikitext-2-raw-v1', model_args={}))
[2023-10-09 19:44:12,925] [INFO] [agent.py:149:_launch_workers] Launching worker 0...
[2023-10-09 19:44:12,927] [INFO] [agent.py:149:_launch_workers] Launching worker 1...
[2023-10-09 19:44:14,649] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-10-09 19:44:15,106] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-10-09 19:44:17,202] [INFO] [worker.py:22:worker_main] Initializing Oobleck Engine...
/home/ytyang/anaconda3/envs/oobleck/lib/python3.10/site-packages/transformers/training_args.py:1270: FutureWarning: using `no_cuda` is deprecated and will be removed in version 5.0 of 🤗 Transformers. Use `use_cpu` instead
  warnings.warn(
[2023-10-09 19:44:17,676] [INFO] [worker.py:22:worker_main] Initializing Oobleck Engine...
/home/ytyang/anaconda3/envs/oobleck/lib/python3.10/site-packages/transformers/training_args.py:1270: FutureWarning: using `no_cuda` is deprecated and will be removed in version 5.0 of 🤗 Transformers. Use `use_cpu` instead
  warnings.warn(
[2023-10-09 19:44:21,706] [INFO] [engine.py:474:_initialize_engine] model arguments: {}
[2023-10-09 19:44:21,718] [INFO] [engine.py:474:_initialize_engine] model arguments: {}
mb size: 14, ar across: 14, ar in: 14
Loading done. creating layer execution results...
Returning from get_profiler_results
[2023-10-09 19:44:22,301] [INFO] [engine.py:514:_initialize_engine] Number of nodes range: (1, 2)
Creating tasks for 1 nodes
Creating tasks for 2 nodes
Waiting for tasks for 1 nodes
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/home/ytyang/anaconda3/envs/oobleck/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ytyang/anaconda3/envs/oobleck/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ytyang/Oobleck/oobleck/elastic/worker.py", line 23, in worker_main
    engine = OobleckEngine(local_rank, num_nodes, num_gpus_per_node, pipe, args)
  File "/home/ytyang/Oobleck/oobleck/execution/engine.py", line 455, in __init__
    ) = self._initialize_engine(self._num_nodes, self._num_gpus_per_node)
  File "/home/ytyang/Oobleck/oobleck/execution/engine.py", line 520, in _initialize_engine
    ] = template_generator.create_pipeline_templates(
IndexError: map::at
mb size: 14, ar across: 14, ar in: 14
Loading done. creating layer execution results...
Returning from get_profiler_results
[2023-10-09 19:44:22,391] [INFO] [engine.py:514:_initialize_engine] Number of nodes range: (1, 2)
Creating tasks for 1 nodes
Creating tasks for 2 nodes
Waiting for tasks for 1 nodes
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/home/ytyang/anaconda3/envs/oobleck/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ytyang/anaconda3/envs/oobleck/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ytyang/Oobleck/oobleck/elastic/worker.py", line 23, in worker_main
    engine = OobleckEngine(local_rank, num_nodes, num_gpus_per_node, pipe, args)
  File "/home/ytyang/Oobleck/oobleck/execution/engine.py", line 455, in __init__
    ) = self._initialize_engine(self._num_nodes, self._num_gpus_per_node)
  File "/home/ytyang/Oobleck/oobleck/execution/engine.py", line 520, in _initialize_engine
    ] = template_generator.create_pipeline_templates(
IndexError: map::at
Task exception was never retrieved
future: <Task finished name='Task-8' coro=<OobleckAgent.on_receive_reconfiguration() done, defined at /home/ytyang/Oobleck/oobleck/elastic/agent.py:217> exception=BrokenPipeError(32, 'Broken pipe')>
Traceback (most recent call last):
  File "/home/ytyang/Oobleck/oobleck/elastic/agent.py", line 232, in on_receive_reconfiguration
    worker.pipe.send(lost_node_ip)
  File "/home/ytyang/anaconda3/envs/oobleck/lib/python3.10/multiprocessing/connection.py", line 211, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/ytyang/anaconda3/envs/oobleck/lib/python3.10/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/home/ytyang/anaconda3/envs/oobleck/lib/python3.10/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

```

There seem to be errors in the function `template_generator.create_pipeline_templates`. Can you provide any guidance on how to address this issue? Any help would be appreciated.

**Comment by insujang** [comment]
Hi, Thank you for trying to use Oobleck.

I think profile was only done with one node, so that trying to create pipeline templates for two nodes failed. Please remove `/tmp/oobleck/profiles/<model_name>` directory and rerun. It will profile the model again using two nodes and create pipeline templates.
I will improve the implementation so that based on metadata how many nodes are used for profiling to avoid such error in the future. Thanks for reporting!

**Comment by yyyyyt123** [comment]
Thanks for your help! The problem is solved.
